version: '3.9'

services:
  core:
    build: .
    container_name: $CONTAINER_NAME
    image: $IMAGE_NAME
    command: sh ./script.sh
    env_file:
      - .env
    volumes: 
      - .:/app
    ports:
      - $SERVER_PORT:$SERVER_PORT
      